from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'Event',
    'User',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'Event': {
        'author': 'User',
    },
    'User': {
        'events': 'Event',
    },
}

# fmt: on